# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoBoard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('mail', models.CharField(blank=True, max_length=50)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('hits', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
