# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20160916_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='memo',
        ),
        migrations.AddField(
            model_name='board',
            name='contents',
            field=models.TextField(blank=True),
        ),
    ]
