# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20160917_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('depth_id', models.PositiveSmallIntegerField()),
                ('reply', models.TextField()),
                ('name', models.TextField()),
                ('password', models.CharField(max_length=256)),
                ('ipaddress', models.CharField(max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_id', to='board.Board')),
            ],
        ),
    ]
