# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='board_id',
        ),
        migrations.AddField(
            model_name='reply',
            name='board',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='board.Board'),
        ),
    ]
