# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20160919_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='depth_id',
        ),
        migrations.AddField(
            model_name='reply',
            name='depth',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='parent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
