# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20160922_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
